name: Release New Version

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to actions repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create dist/index.js using ncc tool
        run: |
          cd act_4
          npm init -y
          npm i -g @vercel/ncc
          ncc build index.js

      - name: commit dist/index.js
        run: |
          git config --global user.name 'UnmeshGitHub'
          git config --global user.email 'unmeshtemkar@gmail.com'
          git add --all
          git commit -am "new version for actions 1"
          git push origin main

      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.4
          release_name: Release for act_4 v0.0.4
          draft: false
          prerelease: false